service:
  name: listen2gether

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  statesTableName: ${self:service.name}-states

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.statesTableName}"

functions:
  getAuthUri:
    handler: src/getAuthUri.handler
    events:
      - http:
          method: get
          path: getAuthUri
  getTokens:
      handler: src/getTokens.handler
      events:
        - http:
            method: get
            path: getTokens
  refreshToken:
      handler: src/refreshToken.handler
resources:
    Resources:
        statesTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: states
                AttributeDefinitions:
                  - AttributeName: stateCode
                    AttributeType: S
                KeySchema:
                  - AttributeName: stateCode
                    KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 2
                    WriteCapacityUnits: 2
