export const PAUSE_PLAYBACK = 'PAUSE_PLAYBACK';
export const RESUME_PLAYBACK = 'RESUME_PLAYBACK';
export const PLAY_PLAYBACK = 'PLAY_PLAYBACK';
export const DELETE_ROOM = 'DELETE_ROOM';
export const RECEIVE_LOBBY_UPDATE = 'RECEIVE_LOBBY_UPDATE';
export const RECEIVE_ROOM_UPDATE = 'RECEIVE_ROOM_UPDATE';
export const HIDE_PASSWORD_CONF = 'HIDE_PASSWORD_CONF';
export const SHOW_PASSWORD_CONF = 'SHOW_PASSWORD_CONF';
export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';
export const CHANGE_NICK = 'CHANGE_NICK';
export const SHOW_NEW_ROOM_INPUT = 'SHOW_NEWROOM_INPUT';
export const HIDE_NEW_ROOM_INPUT = 'HIDE_NEW_ROOM_INPUT';
export const RENDER_CHAT = 'RENDER_CHAT';
export const RECEIVE_CHAT_MESSAGE = 'RECEIVE_CHAT_MESSAGE';
export const SET_SONG_MAX_TIME = 'SET_SONG_MAX_TIME';
export const RECEIVE_SONG_TIME_UPDATE = 'RECEIVE_SONG_TIME_UPDATE';
export const ENABLE_TIME_COUNTER = 'ENABLE_TIME_COUNTER';
export const DISABLE_TIME_COUNTER = 'DISABLE_TIME_COUNTER';
export const ADD_PLAYER = 'ADD_PLAYER';
export const OPEN_LOBBY = 'OPEN_LOBBY';
export const CLOSE_LOBBY = 'CLOSE_LOBBY';
export const SET_VOLUME = 'SET_VOLUME';
export const MUTE = 'MUTE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const TICK = 'TICK';
export const SHOW_HELP = 'SHOW_HELP';
export const HIDE_HELP = 'HIDE_HELP';
export const SHOW_ADD_TRACK_DIALOG = 'SHOW_ADD_TRACK_DIALOG';
export const HIDE_ADD_TRACK_DIALOG = 'HIDE_ADD_TRACK_DIALOG';
export const EXIT_ADD_TRACK_DIALOG = 'EXIT_ADD_TRACK_DIALOG';
export const RECEIVE_RESULTS = 'RECEIVE_RESULTS';
export const CHANGE_ACCESS_TOKEN = 'CHANGE_ACCESS_TOKEN';
export const PLAY_TRACK = 'PLAY_TRACK';
export const FINISH_PLAYBACK = 'FINISH_PLAYBACK';
export const BEGIN_PLAYBACK = 'BEGIN_PLAYBACK';
export const RESUME_TRACK = 'RESUME_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const ANULL_PLAYBACK = 'ANULL_PLAYBACK';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const STOP_PLAYBACK = 'STOP_PLAYBACK';
export const SEEK = 'SEEK';

export const pausePlayback = () => ({ type: PAUSE_PLAYBACK });
export const resumePlayback = () => ({ type: RESUME_PLAYBACK });
export const playPlayback = () => ({ type: RESUME_PLAYBACK });
export const deleteRoom = () => ({ type: DELETE_ROOM });
export const receiveLobbyUpdate = (rooms) => ({ type: RECEIVE_LOBBY_UPDATE, rooms });
export const receiveRoomUpdate = (data) => ({
    type: RECEIVE_ROOM_UPDATE, ...data,
});
export const hidePasswordConf = () => ({ type: HIDE_PASSWORD_CONF });
export const showPaswordConf = (roomId) => ({ type: SHOW_PASSWORD_CONF, roomId });
export const showError = (message) => ({ type: SHOW_ERROR, message });
export const hideError = () => ({ type: HIDE_ERROR });
export const changeNick = (nick) => ({ type: CHANGE_NICK, nick });
export const showNewRoomInput = () => ({ type: SHOW_NEW_ROOM_INPUT });
export const hideNewRoomInput = () => ({ type: HIDE_NEW_ROOM_INPUT });
export const renderChat = (val) => ({ type: RENDER_CHAT, val });
export const receiveChatMessage = (message) => ({ type: RECEIVE_CHAT_MESSAGE, message });
export const setSongMaxTime = (songTime) => ({ type: SET_SONG_MAX_TIME, songTime });
export const receiveSongTimeUpdate = (newTime) => ({ type: RECEIVE_SONG_TIME_UPDATE, newTime });
export const enableTimeCounter = () => ({ type: ENABLE_TIME_COUNTER });
export const disableTimeCounter = () => ({ type: DISABLE_TIME_COUNTER });
export const addPlayer = (player) => ({ type: ADD_PLAYER, player });
export const openLobby = () => ({ type: OPEN_LOBBY });
export const closeLobby = () => ({ type: CLOSE_LOBBY });
export const setVolume = (volume) => ({ type: SET_VOLUME, volume });
export const mute = () => ({ type: MUTE });
export const clearErrorMessage = () => ({ type: CLEAR_ERROR_MESSAGE });
export const tick = () => ({ type: TICK });
export const showHelp = () => ({ type: SHOW_HELP });
export const hideHelp = () => ({ type: HIDE_HELP });
export const hideAddTrackDialog = () => ({ type: HIDE_ADD_TRACK_DIALOG });
export const showAddTrackDialog = () => ({ type: SHOW_ADD_TRACK_DIALOG });
export const exitAddTrackDialog = () => ({ type: EXIT_ADD_TRACK_DIALOG });
export const receiveResults = (results) => ({ type: RECEIVE_RESULTS, results });
export const changeAccessToken = (access_token) => ({ type: CHANGE_ACCESS_TOKEN, access_token });
export const playTrack = (trackUri) => ({ type: PLAY_TRACK, trackUri });
export const finishPlayback = () => ({ type: FINISH_PLAYBACK });
export const beginPlayback = (maxTime) => ({ type: BEGIN_PLAYBACK, maxTime });
export const resumeTrack = () => ({ type: RESUME_TRACK });
export const pauseTrack = () => ({ type: PAUSE_TRACK });
export const anullPlayback = () => ({ type: ANULL_PLAYBACK });
export const setAccessToken = (access_token) => ({ type: SET_ACCESS_TOKEN, access_token });
export const stopPlayback = () => ({ type: STOP_PLAYBACK });
export const seek = (time) => ({ type: SEEK, time });
