export const REQUEST_CHANGE_NICK = 'REQUEST_CHANGE_NICK';
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE';
export const SEND_DEVICE_ID = 'SEND_DEVICE_ID';
export const REQUEST_PLAY_TRACK = 'REQUEST_PLAY_TRACK';
export const REQUEST_UNPAUSE = 'REQUEST_UNPAUSE';
export const REQUEST_PAUSE = 'REQUEST_PAUSE';
export const REQUEST_MOVE_PLAYBACK = 'REQUEST_MOVE_PLAYBACK';
export const REQUEST_JOIN_ROOM = 'REQUEST_JOIN_ROOM';
export const ALLOW_SEEKING = 'ALLOW_SEEKING';
export const REQUEST_CREATE_ROOM = 'REQUEST_CREATE_ROOM';
export const REQUEST_DELETE_ROOM = 'REQUEST_DELETE_ROOM';
export const REQUEST_LEAVE_ROOM = 'REQUEST_LEAVE_ROOM';
export const REQUEST_TRACK_ADDITION = 'REQUEST_TRACK_ADDITION';
export const REQUEST_TRACK_REMOVAL = 'REQUEST_TRACK_REMOVAL';
export const REQUEST_KICK_CLIENT = 'REQUEST_KICK_CLIENT';
export const REQUEST_SONG_SEARCH = 'REQUEST_SONG_SEARCH';

export const requestChangeNick = (newNick) => ({ type: REQUEST_CHANGE_NICK, newNick });
export const sendChatMessage = (msg) => ({ type: SEND_CHAT_MESSAGE, msg });
export const sendDeviceId = (device_id) => ({ type: SEND_DEVICE_ID, device_id });
export const requestPlayTrack = (trackUri) => ({ type: REQUEST_PLAY_TRACK, trackUri });
export const requestUnpause = () => ({ type: REQUEST_UNPAUSE });
export const requestPause = () => ({ type: REQUEST_PAUSE });
export const requestMovePlayback = (time) => ({ type: REQUEST_MOVE_PLAYBACK, time });
export const requestJoinRoom = (roomId, password) => ({ type: REQUEST_JOIN_ROOM, roomId, password });
export const allowSeeking = () => ({ type: ALLOW_SEEKING });
export const requestCreateRoom = (roomName, password) => ({ type: REQUEST_CREATE_ROOM, roomName, password });
export const requestDeleteRoom = () => ({ type: REQUEST_DELETE_ROOM });
export const requestLeaveRoom = () => ({ type: REQUEST_LEAVE_ROOM });
export const requestPlaylistAddition = (trackUri) => ({ type: REQUEST_TRACK_ADDITION, trackUri });
export const requestPlaylistRemoval = (trackUri) => ({ type: REQUEST_TRACK_REMOVAL, trackUri });
export const requestKickClient = (clientId) => ({ type: REQUEST_KICK_CLIENT, clientId });
export const requestSongSearch = (query, access_token) => ({ type: REQUEST_SONG_SEARCH, query, access_token });
